### PR TITLE
Frontend api calls drafts

### PR DESCRIPTION
**Pull request by logtheman**
Looks like a lot of code but most is boiler plate.
- Added create react app
- edited the package.json and included a lot npm packages needed
- got the api calls to work and communicate with the backend
- plugged in redux and got the initial flow working

LOTS left to do, but I don't want to create a bigger PR.

### CODE REVIEW

**Comment by jerflan** [comment]
@logtheman I cloned this into a separate branch to look at it, but it's not loading. Were there any files that were in git ignore you have to pass over?  I'm assuming just `npm start` to get the client server running, no?

**Comment by logtheman** [comment]
Do npm install to get the dependencies. There may be others I forgot to list in the package.json because I already had them installed globally, so let me know if you end up needing to add more. 

To run, just use rake start. It has a script to start the server on port 3001 and web on 3000

**Comment by jerflan** [comment]
@joanelie  Check the room for troubleshooting if you have merge pains. Make sure you're in the client folder and then run `npm install` and you should be ok. Use `rake start` to start both servers.

**Comment by logtheman** [comment]
@jerflan - I hear ya. With something like this I should have included instructions to get it working since it requires running scripts. Obviously the "react-redux" not being included in the dependencies is just an oversight. I'll make sure to add it in the next PR.

**Pull request merged**
