### PR TITLE
Questions revamp

### PR DESCRIPTION
**Pull request by logtheman**
**Added UI features:**
- New ask questions Modal format
  - changed color, sizing and layout
  - expandable fields on focus
- Reworked questions index layout
  - compact style, but retains top answer similar to Jeremy's original layout 
- Added stick nav logic 
  - Becomes stick upon scrolling past the banner
  - Items shown in navbar are modified when sticky 
- Added search bar that expands upon focus

### CODE REVIEW

**Comment by jerflan** [comment]
We should probably merge both of our changes into master then. What version are you working off of?

**Comment by logtheman** [comment]
@jerflan - we should, but we have merge conflicts I have to figure out how to get rid of. They are all on files where your changes should remain. I just need to get familiar with accepting your changes in the merge =/

**Comment by jerflan** [comment]
Maybe @muffy can guide us, but I'm thinking, I merge what I have right now on back-end-master into master. You pull after that and adjust any conflicts, then merge back in. My changes should overwrite most of your conflicts.

**Comment by logtheman** [comment]
Yeah, this may require some more specialized knowledge (i.e. Muffy). I'm probably doing something wrong, but it keeps pretending I'm up to date. This makes it so that I don't have a way to resolve conflicts. Nice and confused now.

**Pull request merged**
